name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish-npm:
        name: Publish to npm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        services:
            neo4j:
                image: neo4j:4.0.0
                env:
                    NEO4J_AUTH: neo4j/test
                ports:
                    - 7687:7687

    publish-gpr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        services:
            neo4j:
                image: neo4j:4.0.0
                env:
                    NEO4J_AUTH: neo4j/test
                ports:
                    - 7687:7687
