# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing app
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
    test:
        name: Unit test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm ci
            - run: npm test
        services:
            neo4j:
                image: neo4j:4.0.0
                env:
                    NEO4J_AUTH: neo4j/test
                ports:
                    - 7687:7687
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm ci
            - run: npm run lint
    coverage:
        name: Coverage - Coveralls
        runs-on: ubuntu-latest
        needs: [test, lint]
        steps:
            - uses: actions/checkout@v1
            - run: npm ci
            - run: npm run coverage
        services:
            neo4j:
                image: neo4j:4.0.0
                env:
                    NEO4J_AUTH: neo4j/test
                ports:
                    - 7687:7687
