# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing app
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: npm ci
            - run: npm run lint
    coverage:
        name: Test - Coverage - Coveralls
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v1
            - name: Setup
              run: npm ci
            - name: Unit test
              run: npm run test:report
            - name: Coverage
              run: npm run test:coverage
              if: github.ref == 'refs/heads/master'
        services:
            neo4j:
                image: neo4j:4.0.0
                env:
                    NEO4J_AUTH: neo4j/test
                ports:
                    - 7687:7687
